#!/bin/bash

nvcc -O2 htt_main.cu htt.cu -o htt
clear
echo ----------------------------
./htt 10
echo ----------------------------
./htt 11
echo ----------------------------
./htt 12
echo ----------------------------
./htt 13

